
apiVersion: v1 # version
data: #secret detail
  kafka_host: VEJE #encode base64
  kafka_port: VEJE
  db_host: VEJE
  db_port: VEJE
  db_username: VEJE
  db_password: VEJE
  #redis_host: VEJE
  #redis_port: VEJE
  #redis_password: VEJE
  jwt_secret: VEJE
kind: Secret
metadata:
  name: backend #secret name
  namespace: learning #ต้องตรงกับชื่อ namespace ที่สร้างไว้
type: Opaque