server:
  port: 8080
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: "my-awesome-app"
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/backend
    username: postgres
    password: syspass
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 300000

app:
  token:
    secret: m#mySecret@2023
    issuer: BackendService