server:
  port: 8080
spring:
  kafka:
    bootstrap-servers: ${SECRET_KAFKA_HOST:localhost}:${SECRET_KAFKA_PORT:9092}
    consumer:
      group-id: "my-awesome-app"
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${SECRET_DB_HOST:localhost}:${SECRET_DB_PORT:5432}/backend
    username: ${SECRET_DB_USERNAME:postgres}
    password: ${SECRET_DB_PASSWORD:syspass}
  #redis:
  #  host: ${SECRET_DB_REDIS_HOST}
  #  port: ${SECRET_DB_REDIS_PORT}
  #cache:
  #  type: redis
  #  redis:
  #    time-to-live: 300000

app:
  token:
    secret: ${SECRET_JWT_SECRET:'m#mySecret@2023'}
    issuer: BackendService